name: Build Assets

on:
  push:
    branches:
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current branch name
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Get version from branch name
        # 从分支名中获取版本号release/v1.0.0 => 1.0.0
        run: echo "VERSION=$(echo $BRANCH_NAME | sed 's/release\/v//g')" >> $GITHUB_ENV

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build:vusion

      # 创建一个临时目录
      - name: Create temp dir
        run: mkdir temp && cp -r ./dist-theme ./temp/dist-theme && cp -r ./assets-package/src ./temp/src && cp -r ./assets-package/src-vusion ./temp/src-vusion

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: 'mobile-ui@${{ env.VERSION }}'
          path: temp
