name: Build Assets

on:
  push:
    branches:
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current branch name
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Get version from branch name
        # 从分支名中获取版本号release/v1.0.0 => 1.0.0
        run: echo "VERSION=$(echo $BRANCH_NAME | sed 's/release\/v//g')" >> $GITHUB_ENV

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: LCAP_LIB_VERSION=${{ env.VERSION }} yarn build:theme

      # 创建一个临时目录
      - name: Create Assets
        run: LCAP_LIB_VERSION=${{ env.VERSION }} node bin/asset.js

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mobile-ui@${{ env.VERSION }}
          path: mobile-ui@${{ env.VERSION }}
  call-wexler:
    needs: build
    uses: vusion/wexler/.github/workflows/release-vant.yml@master
    secrets: inherit
